/**
 * Annotations vente à emporter / présence Uber Eats pour la liste de
 * départ (ajout du 26/09/2026, demande de Krys). Déterminées par
 * recherche web classique (site officiel du commerce, réseaux sociaux,
 * office de tourisme) -- JAMAIS en consultant ubereats.com/deliveroo.fr/
 * justeat.fr directement (même limite déjà appliquée à la constitution
 * de la liste elle-même, voir prospectSeedData.ts).
 *
 * offersTakeaway : null = pas d'info claire trouvée, true/false = vérifié.
 * advertisesUberEats : true SEULEMENT si le commerce affiche lui-même un
 * lien/bandeau Uber Eats sur son propre site ou ses réseaux -- ne veut PAS
 * dire "absent d'Uber Eats" si false/null, juste "aucune mention trouvée".
 *
 * Importé via POST /api/admin/prospects/annotate (bouton "Vérifier vente à
 * emporter / Uber Eats" sur la page Prospection) -- met à jour les lignes
 * déjà en base par (nom, ville), et SUPPRIME celles où offersTakeaway est
 * explicitement false (Krys a demandé à retirer celles qui ne font pas de
 * vente à emporter -- jamais celles en null, juste pas encore confirmées).
 */

export interface ProspectAnnotation {
  businessName: string;
  city: string;
  offersTakeaway: boolean | null;
  advertisesUberEats: boolean | null;
}

export const PROSPECT_ANNOTATIONS: ProspectAnnotation[] = [
  { businessName: "La Tarte Tropézienne", city: "Saint-Tropez", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Pizza Tropézienne", city: "Saint-Tropez", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Allo Pizzas Saint-Tropez", city: "Saint-Tropez", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Boucherie Arnaud", city: "Saint-Tropez", offersTakeaway: null, advertisesUberEats: null },
  { businessName: "Boucherie Thierry", city: "Saint-Tropez", offersTakeaway: null, advertisesUberEats: null },
  { businessName: "Aux Deux Frères", city: "Saint-Tropez", offersTakeaway: true, advertisesUberEats: null },
  { businessName: "Boulangerie des Oliviers", city: "Saint-Tropez", offersTakeaway: true, advertisesUberEats: null },
  { businessName: "Lou Pistou (traiteur)", city: "Saint-Tropez", offersTakeaway: true, advertisesUberEats: null },
  { businessName: "Chez Madeleine (traiteur)", city: "Saint-Tropez", offersTakeaway: true, advertisesUberEats: null },
  { businessName: "L'Aroma Pizzeria Contemporaine Au Feu de Bois", city: "Saint-Tropez", offersTakeaway: true, advertisesUberEats: true },
  { businessName: "La Ponche", city: "Saint-Tropez", offersTakeaway: false, advertisesUberEats: false },
  { businessName: "Le Goustado Tropézien", city: "Saint-Tropez", offersTakeaway: null, advertisesUberEats: null },
  { businessName: "Au Caprice des Deux", city: "Saint-Tropez", offersTakeaway: false, advertisesUberEats: false },
  { businessName: "Gustaveur", city: "Gassin", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Restaurant Au Vieux Gassin", city: "Gassin", offersTakeaway: false, advertisesUberEats: false },
  { businessName: "La Ciboulette", city: "Gassin", offersTakeaway: null, advertisesUberEats: null },
  { businessName: "Boulangerie Pâtisserie Salon de Thé Marc Antoine", city: "Gassin", offersTakeaway: true, advertisesUberEats: null },
  { businessName: "Restaurant Bello Visto", city: "Gassin", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Restaurant Le Pescadou", city: "Gassin", offersTakeaway: false, advertisesUberEats: false },
  { businessName: "Restaurant La Verdoyante", city: "Gassin", offersTakeaway: false, advertisesUberEats: false },
  { businessName: "Restaurant Le G (Golf Country Club)", city: "Gassin", offersTakeaway: null, advertisesUberEats: null },
  { businessName: "Le Will", city: "Ramatuelle", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "La Ferme Ladouceur", city: "Ramatuelle", offersTakeaway: null, advertisesUberEats: null },
  { businessName: "Atelier de la Forge", city: "Ramatuelle", offersTakeaway: true, advertisesUberEats: null },
  { businessName: "Café de l'Ormeau", city: "Ramatuelle", offersTakeaway: null, advertisesUberEats: null },
  { businessName: "Boulangerie Pâtisserie Au Cœur de Ramatuelle", city: "Ramatuelle", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Cybèle Ramatuelle", city: "Ramatuelle", offersTakeaway: null, advertisesUberEats: false },
  { businessName: "Loulou in Ramatuelle", city: "Ramatuelle", offersTakeaway: null, advertisesUberEats: false },
  { businessName: "La Terrasse du Baou", city: "Ramatuelle", offersTakeaway: false, advertisesUberEats: false },
  { businessName: "La Grimaudoise", city: "Grimaud", offersTakeaway: null, advertisesUberEats: false },
  { businessName: "La Caravelle (Caravelle Yachting)", city: "Grimaud", offersTakeaway: null, advertisesUberEats: false },
  { businessName: "Pasta & Via", city: "Grimaud", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Don Peppe", city: "Grimaud", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "La Table du Mareyeur", city: "Grimaud", offersTakeaway: null, advertisesUberEats: false },
  { businessName: "La Provençale & Paul", city: "Grimaud", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "La Marée", city: "Grimaud", offersTakeaway: null, advertisesUberEats: false },
  { businessName: "Le Grand Pin", city: "Grimaud", offersTakeaway: null, advertisesUberEats: false },
  { businessName: "Lou Gâté", city: "Grimaud", offersTakeaway: null, advertisesUberEats: false },
  { businessName: "Chez Nous", city: "Cogolin", offersTakeaway: null, advertisesUberEats: false },
  { businessName: "La Petite Maison", city: "Cogolin", offersTakeaway: false, advertisesUberEats: false },
  { businessName: "Le Cauvet", city: "Cogolin", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "La Grange des Agapes", city: "Cogolin", offersTakeaway: false, advertisesUberEats: false },
  { businessName: "Open Bistro", city: "Cogolin", offersTakeaway: null, advertisesUberEats: false },
  { businessName: "Oliva Nera", city: "Cogolin", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Au Comptoir Thaï", city: "Cogolin", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Boulangerie Esterellas", city: "Cogolin", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "La Maison du Boulanger", city: "Cogolin", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Pâtisserie du Platane", city: "Cogolin", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Boucherie Le Régal", city: "Cogolin", offersTakeaway: null, advertisesUberEats: false },
  { businessName: "Boucherie Deschaseaux", city: "Cogolin", offersTakeaway: null, advertisesUberEats: false },
  { businessName: "L'Atelier Provençal", city: "Cogolin", offersTakeaway: null, advertisesUberEats: false },
  { businessName: "Agapes Traiteur", city: "Cogolin", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "La Belle Fermière", city: "Cogolin", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Le Café de France", city: "Sainte-Maxime", offersTakeaway: null, advertisesUberEats: false },
  { businessName: "La Gruppi", city: "Sainte-Maxime", offersTakeaway: null, advertisesUberEats: false },
  { businessName: "Les Flambeaux", city: "Sainte-Maxime", offersTakeaway: null, advertisesUberEats: false },
  { businessName: "Café Maxime", city: "Sainte-Maxime", offersTakeaway: null, advertisesUberEats: false },
  { businessName: "Hostellerie La Belle Aurore (La Table d'Aurore)", city: "Sainte-Maxime", offersTakeaway: false, advertisesUberEats: false },
  { businessName: "Boucherie Pouzadoux", city: "Sainte-Maxime", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Traiteur Le Maxime", city: "Sainte-Maxime", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Saveurs du Brésil", city: "Sainte-Maxime", offersTakeaway: true, advertisesUberEats: true },
  { businessName: "Restaurant Fred", city: "Sainte-Maxime", offersTakeaway: null, advertisesUberEats: false },
  { businessName: "Moulin de Païou", city: "Sainte-Maxime", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Café Valmer", city: "La Croix-Valmer", offersTakeaway: null, advertisesUberEats: false },
  { businessName: "Le Nautic Beach", city: "La Croix-Valmer", offersTakeaway: null, advertisesUberEats: false },
  { businessName: "La Fine Bouche", city: "La Croix-Valmer", offersTakeaway: null, advertisesUberEats: false },
  { businessName: "Boulangerie Roux", city: "La Croix-Valmer", offersTakeaway: null, advertisesUberEats: false },
  { businessName: "Boucherie Chez Jérôme", city: "La Croix-Valmer", offersTakeaway: null, advertisesUberEats: false },
  { businessName: "Pizz'burger", city: "La Croix-Valmer", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Boulangerie des Palmiers", city: "La Croix-Valmer", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Château de Valmer - Restaurant La Palmeraie / Le Jardin", city: "La Croix-Valmer", offersTakeaway: false, advertisesUberEats: false },
  { businessName: "Le Bouchon", city: "La Garde-Freinet", offersTakeaway: null, advertisesUberEats: false },
  { businessName: "La Faücado", city: "La Garde-Freinet", offersTakeaway: null, advertisesUberEats: false },
  { businessName: "La Petite Fontaine", city: "La Garde-Freinet", offersTakeaway: null, advertisesUberEats: false },
  { businessName: "Ultimate Provence (UP Restaurant)", city: "La Garde-Freinet", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Bar du Soleil", city: "La Garde-Freinet", offersTakeaway: null, advertisesUberEats: null },
  { businessName: "La Table de Miremer", city: "La Garde-Freinet", offersTakeaway: null, advertisesUberEats: null },
  { businessName: "La Table d'Angèle", city: "La Garde-Freinet", offersTakeaway: null, advertisesUberEats: null },
  { businessName: "Restaurant La Tour du Plan", city: "Plan-de-la-Tour", offersTakeaway: null, advertisesUberEats: null },
  { businessName: "Boulangerie-Pâtisserie Céline & Micka", city: "Plan-de-la-Tour", offersTakeaway: null, advertisesUberEats: null },
  { businessName: "Ô Plan Restô Bistrô", city: "Plan-de-la-Tour", offersTakeaway: null, advertisesUberEats: null },
  { businessName: "Le Comptoir de la Poste", city: "Plan-de-la-Tour", offersTakeaway: true, advertisesUberEats: null },
  { businessName: "Pizza Vallaury", city: "Plan-de-la-Tour", offersTakeaway: true, advertisesUberEats: null },
  { businessName: "Chez Bastianin", city: "Plan-de-la-Tour", offersTakeaway: null, advertisesUberEats: null },
  { businessName: "Restaurant Mauricette", city: "Plan-de-la-Tour", offersTakeaway: true, advertisesUberEats: null },
  { businessName: "Restaurant L'Hacienda Plan de la Tour", city: "Plan-de-la-Tour", offersTakeaway: true, advertisesUberEats: null },
  { businessName: "Auberge de la Mole", city: "La Mole", offersTakeaway: null, advertisesUberEats: null },
  { businessName: "Boulangerie-Pâtisserie Martial", city: "La Mole", offersTakeaway: true, advertisesUberEats: null },
  { businessName: "David Millet Artisan Traiteur", city: "La Mole", offersTakeaway: null, advertisesUberEats: null },
  { businessName: "Le Magnan", city: "La Mole", offersTakeaway: null, advertisesUberEats: null },
  { businessName: "L'Escale Tropézienne", city: "La Mole", offersTakeaway: null, advertisesUberEats: null },
  { businessName: "La Maison de Julie", city: "La Mole", offersTakeaway: null, advertisesUberEats: null },
  { businessName: "Le Bistrot Gourmet", city: "La Mole", offersTakeaway: true, advertisesUberEats: null },
  { businessName: "La Baraque Bleue", city: "Saint-Tropez", offersTakeaway: true, advertisesUberEats: null },
  { businessName: "Maison Marguerite", city: "Saint-Tropez", offersTakeaway: null, advertisesUberEats: null },
  { businessName: "Snack Croc A Tout Kebab & Tacos", city: "Saint-Tropez", offersTakeaway: true, advertisesUberEats: null },
  { businessName: "Snack La Palmeraie", city: "Saint-Tropez", offersTakeaway: true, advertisesUberEats: null },
  { businessName: "Papy Burger", city: "Saint-Tropez", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "LuLu Sandwich Shop", city: "Saint-Tropez", offersTakeaway: true, advertisesUberEats: null },
  { businessName: "Rolls Café", city: "Saint-Tropez", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Gaby", city: "Saint-Tropez", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Palmito", city: "Saint-Tropez", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Kaja Poke & Juice", city: "Saint-Tropez", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Snack Elfi's Comptoir gourmand", city: "Gassin", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Snack Tropical Golf", city: "Gassin", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "La Tour De Pizz", city: "Gassin", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Snack Lou Ravi", city: "Ramatuelle", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "La Grignote", city: "Ramatuelle", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Café Flora", city: "Ramatuelle", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Chez Lolo", city: "Ramatuelle", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Cucina de La Forge", city: "Ramatuelle", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Le Petit Bain", city: "Grimaud", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Yeellow Smash Burger", city: "Grimaud", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Pohmaë Poke Bowl Port Grimaud", city: "Grimaud", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Pizza Italia", city: "Grimaud", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Pizza Leone", city: "Grimaud", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Crêperie Le Boubou", city: "Grimaud", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Pummarola", city: "Grimaud", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "La Détente Snack/Kebab", city: "Cogolin", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Pizz'Arte", city: "Cogolin", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Pizza Plus", city: "Cogolin", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Pizza du Golfe", city: "Cogolin", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Hot Pizza Ristorante", city: "Cogolin", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Le Kotama", city: "Cogolin", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "L'orienthe", city: "Cogolin", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "cÔcotte", city: "Cogolin", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Speedy Pizza", city: "Cogolin", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "My Snack La Nartelle", city: "Sainte-Maxime", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Pizzas Manon", city: "Sainte-Maxime", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Ciao Belli", city: "Sainte-Maxime", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Little Café", city: "Sainte-Maxime", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Géo Glacier", city: "Sainte-Maxime", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "La Grange Crêperie", city: "Sainte-Maxime", offersTakeaway: null, advertisesUberEats: false },
  { businessName: "Coco Glaces", city: "Sainte-Maxime", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "The Pizza House", city: "La Croix-Valmer", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Jo Pizza La Croix Valmer", city: "La Croix-Valmer", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Pipo Pizza", city: "La Garde-Freinet", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Pizza L'Escapade", city: "La Garde-Freinet", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Le Carnotzet", city: "La Garde-Freinet", offersTakeaway: null, advertisesUberEats: false },
  { businessName: "Le Petit Freinet", city: "La Garde-Freinet", offersTakeaway: null, advertisesUberEats: false },
  { businessName: "Snack Le Détour", city: "Plan-de-la-Tour", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "O'snacking", city: "Plan-de-la-Tour", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Pizza Bella (food truck)", city: "Plan-de-la-Tour", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Pizza Pierrot", city: "Plan-de-la-Tour", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Le Café", city: "La Mole", offersTakeaway: null, advertisesUberEats: false },
  { businessName: "Yoka", city: "La Mole", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Pacha Café", city: "La Mole", offersTakeaway: true, advertisesUberEats: false },

  // Les 11 suivants viennent de la recherche Uber Eats "Sainte-Maxime" faite
  // par Krys elle-même (capture d'écran) -- vue directement listés sur Uber
  // Eats par la cliente, donc advertisesUberEats: true en confiance.
  { businessName: "McDonald's Sainte-Maxime", city: "Sainte-Maxime", offersTakeaway: true, advertisesUberEats: true },
  { businessName: "Burger King", city: "Gassin", offersTakeaway: true, advertisesUberEats: true },
  { businessName: "Hatsuke Japanese Food", city: "Saint-Tropez", offersTakeaway: true, advertisesUberEats: true },
  { businessName: "Pizza & Basta !", city: "Sainte-Maxime", offersTakeaway: true, advertisesUberEats: true },
  { businessName: "Pizzas Du Golfe", city: "Sainte-Maxime", offersTakeaway: true, advertisesUberEats: true },
  { businessName: "Professeur Burger", city: "Sainte-Maxime", offersTakeaway: true, advertisesUberEats: true },
  { businessName: "Le Petit Sushi", city: "Cogolin", offersTakeaway: true, advertisesUberEats: true },
  { businessName: "Fraiche", city: "Sainte-Maxime", offersTakeaway: true, advertisesUberEats: true },
  { businessName: "Fatto Bene", city: "Sainte-Maxime", offersTakeaway: true, advertisesUberEats: true },
  { businessName: "La Rôtisserie (Rôtisserie du Marché Couvert)", city: "Sainte-Maxime", offersTakeaway: true, advertisesUberEats: true },
  { businessName: "Poké Sainte-Maxime", city: "Sainte-Maxime", offersTakeaway: true, advertisesUberEats: true },

  // Ajout du 26/09/2026 -- annotations pour les 59 établissements de la
  // recherche systématique snacks/fast-food ville par ville (voir
  // prospectSeedData.ts pour le détail). offersTakeaway: true pour tous
  // (catégorie de recherche = snack/vente à emporter par définition).
  // advertisesUberEats: false par défaut -- aucune inscription Uber Eats
  // confirmée par recherche web classique pour ce lot (on ne va jamais
  // vérifier directement sur Uber Eats, voir la règle en tête de fichier).
  { businessName: "Times Food", city: "Sainte-Maxime", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Allo Pizza & Tacos", city: "Sainte-Maxime", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Sun Café", city: "Sainte-Maxime", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Le Manoir", city: "Sainte-Maxime", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Gourmet Kebab", city: "Sainte-Maxime", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "La Dolce Vita", city: "Sainte-Maxime", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Le Pétrin Ribeïrou", city: "Sainte-Maxime", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Le Maximois", city: "Sainte-Maxime", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Paris Plage", city: "Sainte-Maxime", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Dux", city: "Saint-Tropez", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "King Food", city: "Saint-Tropez", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "La Pause de Saint-Tropez", city: "Saint-Tropez", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Los Tacos Saint-Tropez", city: "Saint-Tropez", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Falafel & Co", city: "Saint-Tropez", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Chez Sabrina", city: "Saint-Tropez", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Les Heures Sandwiches", city: "Saint-Tropez", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Casa del Taco", city: "Cogolin", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Miami Burger Golfe de Saint-Tropez", city: "Cogolin", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Snack Jazia", city: "Cogolin", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Friterie l'Officine", city: "Cogolin", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Wokitchen", city: "Cogolin", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Papa's Pizza", city: "Cogolin", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Pizzas du Jardin", city: "Cogolin", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Sushi Maki Store", city: "Cogolin", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "KSB Kebab Sandwich Burger", city: "Grimaud", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Los Tacos Var", city: "Grimaud", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "So Salade So Pizzas", city: "Grimaud", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Les Baigneuses", city: "Grimaud", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Le Pic Nic", city: "Grimaud", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Just'in truck", city: "Grimaud", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "McDonald's Gassin", city: "Gassin", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Papy Burger", city: "Gassin", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Easy Sushi", city: "Gassin", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Pizzeria Don Peppe 3.0", city: "Gassin", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Rôtisserie d'Azur Park", city: "Gassin", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Histoire de Pains", city: "Gassin", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Paul", city: "Gassin", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Casino Cafétéria", city: "Gassin", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "TONO Pampelonne", city: "Ramatuelle", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Tahiti Grill & Pizza", city: "Ramatuelle", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Charly'z Buvette", city: "Ramatuelle", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Snack de la Cabane Bambou", city: "Ramatuelle", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Snack du Migon", city: "Ramatuelle", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Cap 21 - Les Murènes (snack)", city: "Ramatuelle", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Snack du Club 55", city: "Ramatuelle", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Snack Popeye", city: "La Croix-Valmer", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Le Snack", city: "La Croix-Valmer", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Il Forno (Bellamoli)", city: "La Croix-Valmer", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Le Patio", city: "La Croix-Valmer", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Up Up Burger", city: "La Croix-Valmer", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Le Petit Gigaro", city: "La Croix-Valmer", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Nono Pizza", city: "La Croix-Valmer", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Rapid Pizza", city: "La Croix-Valmer", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Vie la joie Bistrot", city: "La Garde-Freinet", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "La Fuente", city: "La Garde-Freinet", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Drogheria Italiana", city: "Plan-de-la-Tour", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Le Comptoir des Terroirs", city: "Plan-de-la-Tour", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "Porte Verte Guinguette", city: "Plan-de-la-Tour", offersTakeaway: true, advertisesUberEats: false },
  { businessName: "La Tarte Tropézienne (Plan-de-la-Tour Centre-ville)", city: "Plan-de-la-Tour", offersTakeaway: true, advertisesUberEats: false },
];
